name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  bun-version:
    description: Version of Bun to use
    default: 1.1.42

  eas-version:
    description: Version of EAS CLI to use
    default: latest

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}
        
    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: bun install
      shell: bash

    - name: ♻️ Restore cache
      uses: actions/cache@v4
      with:
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}
        path: |
          node_modules/.cache/turbo
          apps/*/.turbo
          packages/*/.turbo